- _433nIRtoMQTTto433nIR_ESP8266.ino
- _433toMQTTto433_ESP8266.ino
if you want to avoid duplicate mqtt message received set time_avoid_duplicate to > 0, the value is the time in milliseconds during which we don't publish duplicates
> #1 -  feature to remove duplicates RF -->MQTT

- _433nIRtoMQTTto433nIR_ESP8266.ino
A standard function exists to convert c-style strings to unsigned longs.
https://linux.die.net/man/3/strtoul
> Use strtoul() instead of custom code.

- FanRemoteGPIO.cpp
- FanRemoteGPIO.h
- README.md
- _433toMQTTto433nFan_ESP8266.ino
I'm not sure this is worth approving, but I had a fun time hacking together support for controlling a very-much non-433mhz fan remote control kit I purchased. :) 
Thanks for putting this project online with such easy instructions; I started using it last week for my various power outlets (byebye standby and of course the Etekcity ones everyone uses) and it worked beautifully!
> Control a fan via wiring gpio pins to remote

- .travis.yml
- OpenMQTTGateway.ino
- README.md
- User_config.h
Added Support for OTA-Updates for the ESP8266-Boards (e.g. NodeMCU)
> related to #52

- README.md
Some minor spelling errors.
Some formatting errors where capitalisation was a bit of.
Reordered some of the information.
Removed example at the end.
Added supported devices to first list from second list.
I'll submit one with only the formatting and spelling if you prefer the original layout.
> Formatting and spelling suggestions

- ZgatewayIR.ino
- ZsensorBH1750.ino
- ZsensorBME280.ino
https://www.codacy.com/app/1technophile/OpenMQTTGateway/dashboard
> some minor correction after codacy checks

- User_config.h
- ZgatewayBT.ino
> add hm-11 support

- ZgatewayRFM69.ino
- config_RFM69.h
Replaces this pull request : https://github.com/1technophile/OpenMQTTGateway/pull/124
- Fixes the wrong RFM69 submodule
- Makes publishing the RSSI configurable.
> Some code clean, and buffer overflow prevention (2)

- README.md
Cleanup of the formatting of the Readme.
> Cleanup formatting of Readme

- OpenMQTTGateway.ino
- User_config.h
- ZsensorINA226.ino
- config_INA226.h
- tests/Test_config.h
> add ina226 sensor

- OpenMQTTGateway.ino
- User_config.h
- ZgatewayBT.ino
- config_DHT.h
- tests/Test_config.h
With ESP32 MDNS causes BLE to don't work properly
#121 
#90 
#83
> Add MDNS for ESP8266

- User_config.h
- tests/Test_config.h
Wi-Fi Network settings were duplicated - removed.
Rearranged the setting lines into relevant sections
Renamed section comment header from Network to MQTT for relevant section
> Fixed Duplicate Network Settings and organized

- ZgatewayBT.ino
[mi jia](https://www.banggood.com/fr/Xiaomi-Mijia-Bluetooth-Thermometer-Hygrometer-with-LCD-Screen-Magnetic-Suction-Wall-Stickers-p-1232396.html?cur_warehouse=CN) temperature and humidity measurement
tested with ESP32 OK
tested with HM10 OK
> add compatibility with mi jia

- OpenMQTTGateway.ino
- User_config.h
- tests/Test_config.h
Avoid that except when OMG has never been connected to MQTT
> When wifi is lost OMG is going to AP mode

- OpenMQTTGateway.ino
- ZsensorGPIOInput.ino
- config_GPIOInput.h
- tests/Test_config.h
This will allow the user to see a closed circuit to ground.  This could be used for a button press, limit switch, float switch etc.
Hopefully I put the PR together correctly this time.  If I am ever in France I owe you a beer because of all the headache I put you through lol.
> GPIOInput Third Time is a Charm!

- ZgatewayBT.ino
- config_BT.h
Mi Jia temperature sensor sends combined message for temperature and humidity. With this modification it is possible to decode also this message type. Also a decoder for the battery status is added.
> Added decode for battery level and combined temperature/humidity

- ZgatewayBT.ino
- config_BT.h
#260 Added support for HASS room presence.
> Add Home Assistant MQTT room presence support (ESP32 only)

- OpenMQTTGateway.ino
- ZactuatorONOFF.ino
- Zgateway2G.ino
- ZgatewayBT.ino
- ZgatewayIR.ino
- ZgatewayRF.ino
- ZgatewayRF2.ino
- ZgatewayRF315.ino
- ZgatewayRFM69.ino
- ZgatewaySRFB.ino
- tests/Test_config.h
simplification of some methods and code size reduction
> Code size reduction

- OpenMQTTGateway.ino
- ZgatewayBT.ino
- ZgatewayIR.ino
- ZgatewayRF.ino
- ZmqttDiscovery.ino
- code size decrease and optim
- add sys measure call for arduino mega
- remove code for managing HM10 with version < v6xx
- replace string by char array comparison
- take mac adress from user_config for arduino ethernet shield
> code cleanup and improvment

- ZgatewayPilight.ino
has been discussed here:
https://github.com/puuu/ESPiLight/issues/39
> correct switch between modes raw versus message + protocol and add raw error codes

- lib/rc-switch/RCSwitch.cpp
In the rc-switch library, protocol 31 (Mertik Maxitrol G6R-H4T1) includes a guard time of 17,000 microseconds. The ON command needs to be transmitted over 80 times for the fireplace to actually switch on. These lengthy delays were causing frequent crashes of the ESP8266 (wdt reset). A new function safeDelayMicroseconds() has been added to replace the usage of the standard delayMicroseconds() function. This new function uses yield() within the delay loop, allowing the ESP to 'breathe' during these delays. After implementing this function and changing the code to make sure the guard delay uses this new function, no more crashes (wdt reset) occur. I have even tested using a repeat count of 200, and the transmission went fine.
Below is an example of how I am using this protocol within Home …
> Use safeDelayMicroseconds() for guard delay to avoid wdt resets

- main/User_config.h
- main/main.ino
- platformio.ini
- test/Test_config.h
-avoid issues with WIFI automatic reconnection on ESP32
-avoid reset of ESP32 when wifi is disconnected
-enable to erase the wifi/mqtt settings if; the mqtt broker wasn't connected once or if the TRIGGER_PIN is pushed for a long time >10s
> Improve wifi connection management

- main/ZgatewayBT.ino
discussed here
https://community.openmqttgateway.com/t/esp32-doesnt-stay-online/570
> add a controller deinit to earn some ble stability

- main/config_IR.h
- platformio.ini
BLE, IR emitter and M5 button detection
> add m5stick-c board

- .travis.yml
setup automatic retrieving and deployment to github release
> auto deployment

- docs/use/actuators.md
- main/ZactuatorONOFF.ino
- main/config_ONOFF.h
- main/main.ino
- prod_env.ini.example
enable to choose the pin when sending the MQTT command
> make ON OFF actuator more flexible

- .travis.yml
- scripts/prepare_deploy.sh
make the use of arduino IDE easier by automating the libraries deposit into github releases
> automate libraries deployment for arduino IDE

- docs/use/ble.md
- main/ZgatewayBT.ino
- main/config_BT.h
Implement RSSI based filtering at build time (MinimumRSSI macro) and runtime, see below:
`mosquitto_pub -t home/OpenMQTTGateway/commands/MQTTtoBT/set -m '{"minrssi":-80}'`
To remove the filtering the value can be set to 0
@maxi1134, would it be possible to test the modification?
> implement minimum rssi filtering

- main/ZgatewayBT.ino
Device integration, this [device ](http://s.click.aliexpress.com/e/tRkOfHT2)advertise by BLE service data the following attributes:
* temperature (tem)
* humidity (hum)
* air pressure (pres)
I added also a new method to recover from the classic cleargrass the temperature and the humidity in the same time. Enabling by the way to have more frequent data from it.
> Add of cleargrass temperature, humidity and air pressure sensor

- platformio.ini
Add both board to automatic build with:
* BLE (both)
* Trigger pin for parameters reset (both)
* IR for m5stick
* Button reading for m5stack
Add also Trigger pin for parameters reset on m5stick-c
> add m5stick & m5stack boards

- docs/.vuepress/config.js
- docs/prerequisites/board.md
- docs/prerequisites/devices.md
- docs/setitup/ir.md
- docs/upload/arduino-ide.md
change link to sources
add credits and some shape for readme
add cleargrass with air pressure and mi band
add PWA
add plugins
Add new boards
improve doc with boards and ble devices
> remove default path when cliking on sidebar menus

- main/ZgatewayBT.ino
- main/main.ino
Bypass issue with ESP32 wifi not reconnecting when some router are restarted:
https://github.com/espressif/arduino-esp32/issues/2501
> Improve Wifi automatic reconnect for ESP32

- main/ZgatewayBT.ino
https://community.home-assistant.io/t/anyone-used-a-plant-sensor-other-than-xaiomi/150868/2
> Add VegTrug (Mi Flora like) sensor

- main/User_config.h
- main/main.ino
- test/Test_config.h
> add wifi advanced setup into user_config.h

- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
- main/main.ino
> publish discovery once at each MQTT connection with retain flag set true

- docs/use/actuators.md
- docs/use/ble.md
- docs/use/gateway.md
- main/User_config.h
- main/ZactuatorONOFF.ino
- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
- main/config_BT.h
- main/main.ino
- test/Test_config.h
correct json buffer size and gateway name
replace state to cmd
to enhance logic
replace set by config
add restart and erase command
add unicity to gateway command switches
BLE devices shouldn't be child of the gateway
make the BTtoMQTT topic consistent with other definitions
> Hass discovery improvments

- main/main.ino
by a dynamic one, and simplify trace function of json objects
> Replace fixed allocation of json buffer

- main/User_config.h
- platformio.ini
reduce gateway name
reduce parameters size
correct issue when using advanced config network
comment simple receiving per default (it is set in platformio.ini when necessary)
> memory optim for UNO

- main/User_config.h
- main/ZgatewayWeatherStation.ino
- main/config_WeatherStation.h
- main/main.ino
- platformio.ini
This PR adds support for these weather stations:
- Venus W174/W132
- Auriol H13726   (tested)
- Hama EWS 1500
- Meteoscan W155/W160
I tested this script on ESP-WROOM-32.
> Add support for weather stations

- main/ZgatewayBT.ino
Alarm clock with BLE temperature and humidity measurement
> Add Qingping Cleargrass CGD1

- main/ZgatewayBT.ino
Removed device_class values unknown to Home-Assistant.
Fixes #570 and fixes #571.
> Fixed invalid device_class values

- main/User_config.h
- main/main.ino
enable after ATTEMPTS_BEFORE_BG
and  ATTEMPTS_BEFORE_BG to try another Wifi protocol
#563
> refactor WIFI connection mng on ESP32 and ESP8266 and enable protocol change

- main/main.ino
https://github.com/espressif/arduino-esp32/issues/2501
>  Bypass for ESP not reconnecting to WIFI automatically the second time

- docs/use/boards.md
- main/User_config.h
- main/ZboardM5.ino
- main/ZgatewayBT.ino
- main/config_BT.h
- main/config_M5.h
- main/main.ino
- platformio.ini
define maxConnectionRetryWifi
put SYStoMQTT at start (before the processing)
> Optimize low power mode code

- docs/setitup/ble.md
- main/ZgatewayBT.ino
- main/config_BT.h
Add some docs to HM10 and set the HM10 speed as a build time macros
> Hm10 details

- docs/prerequisites/devices.md
- docs/use/ble.md
- main/ZgatewayBT.ino
- main/config_BT.h
- main/main.ino
-merge HM10 and ESP32 code
-don't publish service data if recognised
-publish sensor values with the other BLE device parameters to avoid  MQTT multiple publication
-make uniform the case of mac adress id between HM10 and ESP32
-add the possibility to remove service data publishing either when sensors is recognised or not
> Refactor BLE gateways

- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
> [DISCOVERY] replace unit of measurement lu by lx

- main/main.ino
and add parenthesis for better understanding of the comparisons
correct also a non pertinent ;
> Correct endless loop when first connection missed with wifi manual setup

- docs/upload/pio.md
- main/User_config.h
- main/ZgatewayBT.ino
- main/main.ino
Lock BLE scan and MQTT process when OTA is started
> Add a lock mechanism to improve the OTA chances of success with ESP32 and BLE

- main/ZsensorAHTx0.ino
Minor changes to add logic to detect when sensor isn't available on startup or fails read the sensor correctly.
> Ahtx0 detections

- platformio.ini
based on pico32
BT, IR sending available
TODO RGB LED support for gateway status
> Add M5Atom boards support

- scripts/prepare_deploy.sh
updated prepare deploy script to exclude some envs
> Don't publish test builds

- main/ZgatewayBT.ino
- main/config_BT.h
- main/config_mqttDiscovery.h
JQJCY01YM BLE formaldehyde, temperature, humidity and battery
Correct battery sensor publishing for certain devices like Mi Jia LYWSDCGQ
> JQJCY01YM BLE formaldehyde, temperature, humidity and battery sensor integration

- docs/.vuepress/config.js
- docs/participate/adding-protocols.md
- docs/participate/development.md
- docs/participate/support.md
- docs/prerequisites/devices.md
- docs/upload/pio.md
-add JQJCY01YM
-add protocol add guidelines
-minor changes
> Documentation update

- docs/upload/binaries.md
fit with new version of ESP download tool
> [DOC] Binary upload improvement

- main/User_config.h
More parameters are now able to be defined in prod_env.ini, allowing the values in User_config.h to be ignored.
> Allow prod_env.ini parameters to override User_config.h

- platformio.ini
so as to avoid publishing their bin files and confuse users
> [CI] Identify test envs

- docs/use/gateway.md
- main/User_config.h
- main/ZboardM5.ino
- main/ZgatewayBT.ino
- main/main.ino
- platformio.ini
-replace low power led by led info
-enable to change the led ON value
-go upper case for the led macros
-add sonoff rf bridge led
Also transform BLE connect warning to notice in log
> Refactor led management

- main/ZgatewayBT.ino
- main/config_BT.h
> [BT] Remove voltage class

- main/main.ino
> Increase the size of MQTT password

- main/ZgatewayPilight.ino
Fix a bug introduces by PR #776.
> Pilight identifier

- docs/integrate/home_assistant.md
Use json insteal of simplePublishing / receiving
> [DOCS] - integration switch

- main/ZgatewayBT.ino
I bought this one: https://www.aliexpress.com/item/33017088243.html?spm=a2g0s.9042311.0.0.54d44c4dcgD4vs
I received one branded "Qingping" instead of "Cleargrass".
With this patch, the qingping one is now supported
> Add Qingping CGP1W support

- docs/setitup/actuators.md
- docs/setitup/rf.md
- docs/use/actuators.md
- main/User_config.h
- main/ZactuatorSomfy.ino
- main/config_Somfy.h
- main/main.ino
- platformio.ini
Add support for Somfy RTS remote control using https://github.com/Legion2/Somfy_Remote_Lib.
close #814
I can only test with ESP32 and CC1101 module. I also created a platformio env for esp8266.
TODO:
> added ZactuatorSomfy

- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- docs/prerequisites/board.md
- docs/prerequisites/devices.md
- docs/prerequisites/parts.md
- docs/use/actuators.md
- docs/use/ble.md
- package-lock.json
- package.json
added vuepress to package.json to track the used version and make it reproducible and self contained.
cherry picked from #816
> Npm docs setup

- docs/use/gateway.md
- main/User_config.h
> Increase TimeLedON to 1s

- docs/integrate/home_assistant.md
- docs/upload/advanced-configuration.md
- docs/use/gateway.md
- main/ZgatewayBT.ino
- main/ZgatewayRF.ino
- main/ZgatewayRF2.ino
- main/ZmqttDiscovery.ino
- main/ZsensorDS1820.ino
- main/main.ino
and switch automatic creation for it in HASS (by autodiscovery :-)
> Auto discovery deactivation at runtime by MQTT command

- docs/use/boards.md
- main/User_config.h
- main/ZboardM5.ino
- main/ZgatewayBT.ino
- main/ZgatewayRF.ino
- main/ZgatewayRF2.ino
- main/ZmqttDiscovery.ino
- main/ZsensorDS1820.ino
- main/config_mqttDiscovery.h
- main/main.ino
- prod_env.ini.example
-add switch on HASS
-avoid issue when using ESPWifiManualSetup
-Correct issue on gateway discovery on first connect
-publish low power mode and discovery with retain flag
> [Breaking] Improve low power mode

- docs/README.md
Not sure if these changes affect other translations... But I made a few corrections for better understanding in english
> Update readme for better understanding in English

- platformio.ini
> Added Heltec ESP32 Lora board

- README.md
Update github readme for better understanding
> update github readme

- main/ZmqttDiscovery.ino
- main/config_mqttDiscovery.h
> Correct RF2 gateway auto discovery

- main/ZgatewayBT.ino
> Correct build issue when discovery is disable

- main/User_config.h
- main/main.ino
> Correct advanced network parameter setup on ESP

- docs/prerequisites/devices.md
- main/ZgatewayBT.ino
- main/config_BT.h
and remove batt from CGD1 (this sensor does not advertise battery value)
> Add CGDK2 BLE temperature and humidity BLE sensor

- main/ZmqttDiscovery.ino
- main/main.ino
to prevent going to the max of unsigned long
> [BREAKING] Change uptime unit from seconds to minutes

- main/User_config.h
discovery msg and systomqtt require now a bigger buffer
> Increase json buffer

- main/ZmqttDiscovery.ino
- main/main.ino
and revert #897
bypass the millis() max time of 4294967
> Change uptime calculation method

- main/main.ino
> Correct uptime display on trace

- main/User_config.h
768 causes core dump so go back to 512
> Change ESP8266 Json Buffer Size

- main/ZgatewayBT.ino
- main/config_BT.h
> Add BLE setScanDuplicateCacheSize

- docs/integrate/home_assistant.md
- docs/use/ble.md
- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
- main/config_BT.h
And enable to activate it by MQTT
Add a vtaskdelay in the emptyqueue function
> [Breaking] Deactivate Home Assistant presence topic pub per default
