1technophile/OpenMQTTGateway

- _433nIRtoMQTTto433nIR_ESP8266.ino
Disable Panasonic codes as it is called wrong.
Store data in an unsigned variable, vs a signed on, otherwise it produces bad results for high numbered codes.
Mark protocols that are > 32 bits as they won't work with values large than an unsigned long (32 bits).
> Correct the bit lengths of various IR protocols

- _433nIRtoMQTTto433nIR_ESP8266.ino
> Correct the invocation of Coolix, Sharp, & Dish IR sends.

- OpenMQTTGateway.ino
I think this line should be commented out as the comment suggests.
Everything seemed to work out of the box after the initial set up, I would connect to the WiFi correctly, but then I wouldn't connect to the MQTT broker when that advanced config was uncommented.
I commented it out and everything worked correctly out of the box.
Thanks for your work on this amazing library, I'm looking forward to using it much more in the coming days.
> Comment out the advanced config

- OpenMQTTGateway.ino
When not using advanced network config, the ip is optained via DHCP, so display it after the connection is established. Output was 0.0.0.0 in this case before.
Also adding display of the mac (before connection) for mac address filter config in the wifi-ap.
> Show ip and mac after connect

- .travis.yml
- OpenMQTTGateway.ino
- User_config.h
- ZsensorTSL2561.ino
- config_TSL2561.h
- tests/Test_config.h
I added light intensity measurement based on TSL2561 based modules, such as these from banggood: https://www.banggood.com/GY-2561-TSL2561-Luminosity-Sensor-Breakout-Infrared-Light-Sensor-Module-Integrating-Sensor-AL-p-1129550.html
Dependencies are on Adafruit_TSL2561 and Adafruit_Sensor, as stated in header.
> Add support for TSL2561 based light intensity measurement

- ZgatewayIR.ino
My RC5 based remote requires data to be send 3 times. The functionality for this is mostly implemented, so this is quite a small patch. Reading the code, I see no reason not to introduce the functionality for all remote types (with the exception of raw and GC), considering the support is available in the underlying library. If not set, this defaults to 0 (which sends the data once).
> globally expose repeat functionality as advanced function

- OpenMQTTGateway.ino
- User_config.h
- tests/Test_config.h
The idea is taken from https://www.mysensors.org/build/advanced_gateway
It is working for RF433 and IR module. Probably can be added to the other modules. RED will stay ON until MQTT connection is ready.
> Add support for presenting status with 3 LEDs

- OpenMQTTGateway.ino
- ZsensorADC.ino
- ZsensorBH1750.ino
- ZsensorBME280.ino
- ZsensorDHT.ino
- ZsensorTSL2561.ino
This branch has two goals and one bugfix:
- I noticed in on ESP32 that BME280 sensor readings quite often contained tailing garbage. This is due to several issues with buffer length in the various sensor code files. While incorrect on all platforms, this showed up on ESP32, probably due to a more modern base compiler. This is a classic C-style issue, which I've solved by moving to C++-style dynamically allocated strings. This may use more memory, so perhaps less suitable for arduino boards.
- There were also occasional spikes in the BME280 data. I've attempted to mitigate these by tweaking some of the sensor internal parameters (turned on the filter and significantly increase tStandby). At first glance the results are better.
- Finally, ZsensorADC did not compile on ESP32 for me on line …
> Better sensors

- OpenMQTTGateway.ino
- User_config.h
- ZgatewayRF315.ino
- config_RF315.h
- tests/Test_config.h
based on RF gateway add the same implementation for 315mhz to facilitate the integration for whom who wants to use 433 and 315
> add 315mhz RF gateway

- ZgatewayBT.ino
This PR add a small documentation to make people aware which sensor unit is going to send what kind of data.
> ZgatewayBT.ino: Small documentation for the different sensor signals

- OpenMQTTGateway.ino
if wrong credentials are entered for MQTT connexion, the gateway will go back to AP mode en reenable users to enter their credentials
> go to AP mode if MQTT connexion fail at start

- ZgatewayBT.ino
- config_BT.h
The goal is to enable users to see service data from devices not still integrated to OMG and propose the integrations by analysing servicedata seen on the MQTT broker
> add MQTT publishing of service data from BLE devices

- OpenMQTTGateway.ino
- User_config.h
use #define to remove trace function at build time so as to decrease program size for small memory boards
> Decrease program size if traces off

- OpenMQTTGateway.ino
- ZsensorGPIOKeyCode.ino
- config_GPIOKeyCode.h
This module uses up to 4 gpio pins and creates keycode from bits combination, there is 5th gpio pin used as latch signal - for example it can be used with ev1527 code receiver.
My OpenMQTTGateway in 3d printed case:
https://photos.app.goo.gl/unCdrHzDNx1J68cm6
> multi gpio input module

- lib/rc-switch/RCSwitch.cpp
Introduced with https://github.com/1technophile/OpenMQTTGateway/pull/313
```
/home/johno/Workspaces/rf-tx/main/RCSwitch.cpp: In static member function 'static void RCSwitch::handleInterrupt()':
/home/johno/Workspaces/rf-tx/main/RCSwitch.cpp:835:19: error: suggest parentheses around comparison in operand of '&' [-Werror=parentheses]
if (changeCount > 0 & duration < 100) { // игнорируем шумовые всплески менее 100 мкс
^
cc1plus: some warnings being treated as errors
```
> Fix compile error

- ZgatewayRF.ino
- config_RF.h
Currently the MQTTto433 messages do not support a "repeat" key/value pair. This PR adds support for optionally specifying the number of times an RF message should be transmitted. The default RF_EMITTER_REPEAT remains in effect if "repeat" is not specified in the JSON message.
My use case is a ceiling light which toggles its state upon receipt of the RF signal.
> Add "repeat" field to RF JSON messages.

- ZgatewayIR.ino
This PR fixes #384
The format is now a comma separated list of hex values.
e.g. `14,63,0,10,10,02,FD` in the json it looks like this: `{"datastring":"14,63,0,10,10,02,FD","bits":7,"protocol_name":"IR_FUJITSU_AC","value":1}`
The "bits" must be the count of hex values in the "datastring".
This breaks old datastring usage and users must change the "datastring".
> added IR json datastring hex decoding

- ZgatewayBT.ino
Without the is_defined filter home assistant will reset the value to an empty string every time a topic is posted without the value template. For example when `home/OpenMQTTGateway/BTtoMQTT/--SNIP-- {"moi":2}` is posted - all other sensor with associated topic `home/OpenMQTTGateway/BTtoMQTT/--SNIP--` will get `""` as their value
> Add is_defined filter to the value_template

- main/ZsensorHCSR501.ino
Hello, this is my first code PR on this (awesome) project!
It (hopefully) fixes #306 - in which some users noticed that the HCSR501 module prints the `Creating HCSR501 buffer` message hundreds of times per second (despite working, as I wrote in that issue's comments).
It does so by removing the line that prints the message. It also adds a message for when the movement starts (mostly to match when the movement stops, can remove that or both if those aren't necessary).
My logs on an ESP8266, before the fix:
```
...
23:13:39.036 -> Creating HCSR501 buffer
23:13:39.036 -> Creating HCSR501 buffer
23:13:39.036 -> Creating HCSR501 buffer
23:13:39.036 -> Creating HCSR501 buffer
23:13:39.036 -> Creating HCSR501 buffer
23:13:39.036 -> Creating HCSR501 buffer
23:13:39.036 -> Creating HCSR501 buffer …
```
> Avoid spam of buffer message in hcsr501

- main/main.ino
The DHT module was not being appended to the modules string reported in the SYStoMQTT messages.
I also noticed the code incorrectly references DHT functionality for the INA226 module.
> Correct missing module string for DHT

- main/User_config.h
- main/ZsensorHCSR04.ino
- main/config_HCSR04.h
- main/main.ino
- platformio.ini
Adds support for HC-SR04 Ultrasonic distance sensor.
Note: only tested on a Wemos d1 mini board
> Add support for HC-SR04 sensor

- main/ZgatewayBT.ino
This fixes a bug in single byte values reported in issue #464.
Bug also affected 2 byte and longer values, but in these values first 4 bits seem to be usually irrelevant.
> Fix Mi Flora moisture reading

- main/ZgatewayBT.ino
Home assistant requires unit of measurement for data to display correctly in graphs.
Added unit "µS/cm" for MiFlora Fertility.
Also after fixing single byte issue (PR #465) noticed that MiJia Bluetooth sensor battery unit must be % instead of V. Esphome also uses % as MiJiaBT unit.
I don't have any Xiaomi LYWSD02 or ClearGrass sensor available so not able to check which battery value they are reporting.
> Add Unit of Measurement for MiFlora Fertility and Fix MiJia BT battery to percentage

- .travis.yml
- main/User_config.h
- test/Test_config.h
instead of using harcoded version name use the TRAVIS_TAG environment variable, it recovers the tag name from github.
> [CI] Use travis tag

- .travis.yml
- test/Test_config.h
Solve #518 
Currently the json msg buffer size of binaries produced by the CI is to high for certain boards, in particular the sonoff rf bridge.
This is due to a bad value in test config file used for the continuous integration.
This file is not needed anymore with PIO, so I don't use it on the CI.
Nevertheless I keep it in the repo for a future use with an arduino IDE automated build.
> [CI] Correct wrong json msg buffer size on bin

- main/User_config.h
- main/ZsensorDS1820.ino
- main/config_DS1820.h
- main/main.ino
- platformio.ini
- adds support for Dallas DS1820 1-wire temperature sensors
- requires OneWire and DallasTemperature libraries
- reads temperatures (non-blocking) from multiple sensors
- tested with ESP01 and Wemos D1 mini, the later along with IR/RF modules/peripherals
> module for DS1820 temperature sensor(s)

- main/ZgatewayBT.ino
This patch fixes a fix 'LoadProhibited' in dumpdevice function on my ESP32.
Reason: booleans can not be interpreted as null-terminated strings
I think the source of the problem is that booleans are internally represented as byte and printf (with is called behind Log.trace) try to interpret this byte as a char array with length of 1. But this char array has no null-terminator if the value of the boolean is set to true (with is represented as  1). If the value of the boolean is set to false (0), an empty string will be printed, whats confirms my belief because 0 is also the null-terminator.
Example:
```
BLEDevice device;
device.isDisc = false;
//....
Log.trace(F("isDisc: %d" CR), device->isDisc);
> isDisc:
device.isDisc = true;
//...
Log.trace(F("isDisc: %d" CR), device->isDisc);
> isDisc: …
```
> fix 'LoadProhibited' in dumpdevice

- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
- main/config_BT.h
- main/config_mqttDiscovery.h
Based on my original PR #553 I have further developed the idea to remove duplicate code inside the Bluetooth module step by step to improve the readability and maintainability.
During this, I found a data corruption with is triggered if the white-list is set before the devices are discovered. this is addressed with 92a833eb3d6598b489bf88001fb9a772edd30da2
The last two patches of this series finally reduce the need for device-tree walks and increase the overall speed if many supported ble devices are in range.
Summarizing, these changes save over 141 KB flash size (~9%) and ~600 bytes of memory
> remove duplicate code in main\ZgatewayBT.ino

- main/User_config.h
The `valueAsASubject` was present in two places in the `User_config.h`.
Now it is only in the "MQTT general topics" section.
> Removed duplicated valueAsASubject option in User_config.h

- main/ZgatewayPilight.ino
Set the pin mode of the `RF_EMITTER_PIN` in the `setupPilight`. Actually the pin mode is already set in the ESPiLight constructor, but if the `RF_EMITTER_PIN` is the RX pin the [pin mode is reset](https://github.com/esp8266/Arduino/blob/007e495e0d88eabc6dae31fad311df38f8914607/cores/esp8266/uart.cpp#L714) with the `Serial.end();` call in [main.ino](https://github.com/1technophile/OpenMQTTGateway/blob/development/main/main.ino#L622). So it must be set again.
> Fixed Pilight can not send on RX pin

- docs/setitup/sensors.md
- docs/use/sensors.md
- main/User_config.h
- main/ZmqttDiscovery.ino
- main/ZsensorHTU21.ino
- main/config_HTU21.h
- main/main.ino
- platformio.ini
I ran out of BME280 sensors, but have a bunch of HTU21 sensors. I based the new sensor on the BME80 code. It's basic, but it works on me.
Can be enabled by adding the following to the platform.ini file (in one of the env sections)
lib_deps
${libraries.htu21}
${libraries.wire}
build_flags
'-DZsensorHTU21="HTU21"'
ESP8266 - Uses hardware I2C pins
ESP32 - The SLA/SCL pins can be selected
------------
Successfully compiles for all platforms in the platform.ini file.
Tested on ESP8266 (esp12e) and ESP32 (esp32-cam board) without issues.
> Added HTU21 Sensor

- main/ZgatewayBT.ino
- platformio.ini
- [Issue #593](https://github.com/1technophile/OpenMQTTGateway/issues/593) - Added the condition to address the issue I previously opened to check that Low Power Mode is enabled before making changes to the GPIO pin
- [Issue 591](https://github.com/1technophile/OpenMQTTGateway/issues/591) - Added the WeatherStation libraries and added the module definitions to esp32dev-all and nodemcuv2-all
I don't think any doc changes are needed for these changes, but please let me know if there are any.
> Fixing Issues #593 & #591

- main/ZgatewayBT.ino
- main/config_2G.h
- main/config_ADC.h
- main/config_BT.h
- main/config_DHT.h
- main/config_DS1820.h
- main/config_FASTLED.h
- main/config_HCSR501.h
- main/config_HTU21.h
As mentioned in Issue #595, I've added #ifndef's to several sensors. 
For sensors that require multiple pins, I have it set so the user must specify all required pins in the platformio.ini file. (i.e. For the BT module, the user can't specify the TX pin and use the default RX pin. They must specify both RX and TX pins.)
I did this to force the user to keep all the definitions together, but they can be separated if needed.
If you see any other fields that would benefit from being assigned in the platformio.ini file (like the 2G BAUD rate), let me know and I can add them.
> Allow pins/settings to be defined in INI file

- main/ZsensorHTU21.ino
I found that I had an error in my HTU21 sensor code.
I didn't have the begin() statement inside of the #else directive for non-ESP32 devices.
> HTU21.begin bug fix

- platformio.ini
@Alomon31 from Issue #591 noticed that the WeatherStation library was already in the Platformio.ini file, so my entry was a duplicate. I removed my entry and changed the *-all definitions to use the sensor author's version.
There are also definitions for ATMega to use this library, so I added it to the [env:atmega-all] block.
> Remove duplicate Weatherstation library definition from platformio.ini

- docs/use/ir.md
- main/ZgatewayIR.ino
replace datastring with hex string handling, enable the direct use of an MQTT received hex signal w/o syntax change
correct a bug on protocol identification when the protocol is a derivative of another one and share a common name piece
Following these discussions:
https://community.openmqttgateway.com/t/problems-with-controlling-haier-ac-using-openmqttgateway/972/28
> MQTTtoIR hex handling optim

- docs/use/sensors.md
- main/ZmqttDiscovery.ino
- main/ZsensorDS1820.ino
- main/config_DS1820.h
- main/config_mqttDiscovery.h
Pull Request in response to Issue #598 ; to add HADiscovery for DS18b20 1-Wire sensors
@1technophile 
Looking at the source code and through testing with hardware, I was only able to get 1 sensor at a time to work using the original ZsensorDS1820 code. As it looks as the intention was to allow up to 8 sensors by default, I've modified the following:
-    I changed setupZsensorDS1820 to use the DallasTemperature library to scan the 1-Wire bus and validate that the sensor is a valid DS1820 sensor that can be used instead of using the OneWire library directly.
-    I changed the DS1820 MQTT topic so that all sensors are published as a sub-topic of the DS1820 topic, using their device address as the topic name.
-    Added function to publish the HADiscovery config for each DS1820 device …
> Ds1820 HADiscovery

- main/User_config.h
- main/config_M5.h
- main/main.ino
- test/Test_config.h
and move SLEEP_BUTTON definition to config_M5 as it is only used for the moment with M5 stack and stickc boards
> Per default don't use TRIGGER_GPIO

- docs/upload/arduino-ide.md
- docs/upload/troubleshoot.md
- docs/use/ir.md
- main/User_config.h
- main/main.ino
- platformio.ini
- test/Test_config.h
Thank you for creating (and maintaining!) this fantastic project!
I happened to notice that current versions of `pubsubclient` allow the buffer size to be set
dynamically: https://github.com/knolleary/pubsubclient/pull/282
We can take advantage of this to avoid having to modify one of the
dependencies and instead automatically increase the buffer size when a
powerful board is detected.
It also reduces a step in the documentation.
My first PR to an Arduino project so let me know if I'm doing something
wrong! 😅 🙏 
I suppose this would mean changing the version of the library that is bundled with the
project (`PubSubClient_ID89`?) as well, but I'm not sure how to go about doing so...? 🙇
> Automatically set mqtt buffer size

- main/main.ino
the `.c_str()` is missing in one log call when using mqtt server host name instead of ip.
introduced in #546
> fixed wrong string type after refactoring

- main/main.ino
don't do a manual DNS lookup
I'm working on getting TLS connections to work #101.
I think this is required to enable TLS support as the hostname must be verified by the `WiFiClientSecure`.
> Set the domain name as server of the PubSubClient

- main/User_config.h
- main/main.ino
- test/Test_config.h
I think I started to hit the limit of available RAM in my esp8266's, so I tried setting up ESPWifiManualSetup to save a few Kb's.
In doing so, I found that it wasn't working as expected... or at all.
In the User_config.h `wifi_ssid` and `wifi_password` are set using `#define`, where the `Wifi.begin()` function requires a char[]. An error wasn't being thrown during compile or at runtime in the Serial monitor, but WiFi never connects.
I left the #define's in `User_config.h`, just adding checks to see if they're already set, so they can be set via platformio.ini, and added 2 char[] variables in `main.ino` and assigned them the `User_config.h` values. Doing it this way seemed the least disruptive to users
------
I've also moved the MQTT config variables from the `User_config.h` file into the …
> Fix ESPWifiManualSetup / Move MQTT variables

- docs/integrate/home_assistant.md
- docs/use/sensors.md
- main/ZsensorHCSR501.ino
@1technophile ,
As discussed in issue #690, I've changed the key used for the HCSR501 PIR sensor to be 'presence'. This will fix MQTTDiscovery, but will break users who manually have the sensor setup in HA.
Please let me know if I've missed any other doc locations.
> [Breaking Change] Change HCSR501 MQTT key to 'presence'

- main/ZgatewayBT.ino
from C to F
The division by 10 must be done before the conversion.
> Correct value entered into temperature conversion for BLE devices

- .gitignore
- docs/.vuepress/config.js
- docs/integrate/home_assistant.md
- docs/upload/advanced-configuration.md
- docs/upload/arduino-ide.md
- docs/upload/binaries.md
- docs/upload/pio.md
- docs/upload/troubleshoot.md
- docs/use/ble.md
- docs/use/ir.md
- docs/use/rf.md
- main/User_config.h
- main/main.ino
- platformio.ini
support TLS on ESP32 and ESP8266 close #101
TODO:
> added support for secure TLS connections

- docs/prerequisites/board.md
- docs/prerequisites/devices.md
- main/ZgatewayBT.ino
- platformio.ini
by adding a ArduinoSTL library,
currently the vector function is missing for Arduino AVR boards.
> Enable BT use for Arduino Mega

- docs/use/ble.md
- main/ZgatewayBT.ino
- main/config_BT.h
generalize the use of the mac address with : for the lists, white, black and internal identification
Move structures from config_BT.h to ZgatewayBT.ino
update doc
The goal is to align the vector array ids format with the one extracted from BLEscan
> [breaking] Refactor the BLE devices identification

- main/ZgatewayRF.ino
- main/main.ino
As discussed in issue #715, this will check for duplicate RF/IR signals before storing them in the `receivedSignal` array. This will have a slight performance impact, but should be unnoticeable.
I've also:
- removed a redundant `if` statement from the `receivingMQTT` function
- in the `getMin` function, started the loop on index 1 as index 0 is always the first minimum (no need to check against itself)
- cast the SIGNAL_SIZE_UL_ULL values to a (unsigned long) for Log.trace functions in some functions (uint64_t values aren't supported by the ArduinoLog library)
> Prevent storing duplicate RF/IT signals

- main/ZgatewayBT.ino
@1technophile ,
Sorry, my suggestion broke the loop that adds the ':' into the BT Mac addresses.
> BT MAC addr ':' fix

- main/ZgatewayBT.ino
- main/config_BT.h
- main/main.ino
For the past two weeks I have been investigating random crashes and sometime my OMG losing it's Gateway_Name after a random length of time. (Sometimes 5 minutes, others 3 hours.)
My first thoughts was that I was running out of RAM on my ESP8266 due to running BLE, RF, IR, BME280, PIR, and Analog. Long story short for all my testing, the heap and stack seem to be fine.
However, in the `BTtoMQTT()` method for ESP8266's, the length of the 'Rest Data' is never checked to be less than the decompose.extract[60] buffer. 
https://github.com/1technophile/OpenMQTTGateway/blob/519eb73deee87ae74ffcc48d31cccbf8eb36c83c/main/ZgatewayBT.ino#L607-L611
I believe that this buffer was being overflowed in the main.ino:`extract_char` function when 
https://github.com/1technophile/OpenMQTTGateway/blob/519eb73de …
> BLE Optimizations and buffer overflow fix

- docs/use/ble.md
- main/ZgatewayBT.ino
- main/config_BT.h
don't publish the non identified BLE devices when requested (at build or by MQTT setting)
> Add publish only BLE sensors function

- main/ZgatewayPilight.ino
- main/main.ino
Thank you for this project ;)
The Pilight gateway with the valueAsASubject parameter does not work (compilation problem).
This PR fixes this problem and closes the #408 ticket.
I also added a patch that allows to find a correct ID (in order to have a non null topic) because PiLight only reads ID and ignores the others fields.
One question, in the ZgatewayPilight.ino file, there are this line: `RFPiLightdata.set("length", (char*)deviceID.c_str());` is it normal to set the length value from the deviceID value?
Thank you.
> Fix pilight value as subject

- docs/prerequisites/devices.md
- main/ZgatewayBT.ino
- main/config_BT.h
https://github.com/atc1441/ATC_MiThermometer
https://www.youtube.com/watch?v=NXKzFG61lNs
With this custom firmware, the LYWSD03MMC advertises its data without encryption, so no need to connect to the sensor when using this custom firmware. The data are read every `BLEinterval` like all the other devices that advertise data.
Note that the flashing process takes less than 5minutes and is done over the air (impressive :-)).
> Add LYWSD03MMC from ATC

- platformio.ini
#748
point to main as we are not using default include folder
> Add default include_dir to platformio section

- main/ZgatewayPilight.ino
The `MQTTtoPilight` function's logic prevented the correct parsing of the error codes returned by ESPiLight. This fixes that and somewhat restructures the if/else logic therein for more efficiency.
> Fix ESPiLight transmission error reporting

- docs/use/sensors.md
- main/ZsensorHCSR501.ino
- main/config_HCSR501.h
I've added the option to invert the PIR notification LED at build time. It's default value is set to drive an LED through a Mosfet. If the LED is driven directly from the AVR/ESP's pin, `INVERT_LED_NOTIFY` should be set to `true`.
> Add ability to invert the PIR Notify LED

- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
- main/ZsensorDS1820.ino
from "C" and "F" to "°C and "°F"
> update temperature unit to work in HA

- main/ZgatewayRF.ino
@1technophile, thought of this while minor tweak while testing the HADiscovery from the previous PR.
If the RFGateway is only used to receive and not to transmit, via `RF_DISABLE_TRANSMIT`, is there a reason to create a switch in Home Assistant for the received code?
This PR disables creating a HADiscovery switch when the `RF_DISABLE_TRANSMIT` define is set.
Let me know if you want me to make a note of this in the docs and I'll push an update.
> Dont make HADiscovery switch if RF is receive only

- main/ZgatewayPilight.ino
Add device_id as unique identifier.
> feat: add device_id as unique identifier

- main/ZgatewayRF2.ino
- main/ZmqttDiscovery.ino
Added Home Assistant discovery to RF2.
For each unique combination of unit, groupbit and address a switch will be added to Home Assistant called:  "RF2_[unit]_[groupbit])_[address].
As RF2 433Mhz switches do not render their state, no state topic will be provided in the discovery. 
This will cause the switch to be in optimistic mode in HA with separate on and off icons.  
The two separate on/off icons allow for subsequent on commands to support the dimming feature of KAKU switches like ACM-300.
> Add rf2 autodiscovery

- main/ZgatewayBT.ino
After some tinkering with this project (which I very much like now so congrats for the great work) I spotted a flaw which seems to be pretty critical for me. Maybe someone else is experiencing it also but let's try to give some details first.
**Steps to reproduce:**
- Build a **ESP32** **gateway** that supports Bluetooth also
- Upload firmware via serial
- Configure WiFi and other stuff if this is the first time configuration
- Let it run and monitor the system via `platformio run --target monitor` in another terminal
- After it gets configured and connected to your personal access point try to upload the firmware again using only **OTA** this time
**Expected results:**
- The upload process should go **smooth** until the end with **no failures**
**Actual results:**
- OTA process **fails** …
> [ESP32 OTA] Critical fix - Make sure that the BT coreTask gets suspended when not needed

- docs/integrate/home_assistant.md
Xiaomi Mi Scale V2 BLE (XMTZC05HM) yaml configuration for Home Assistant
Tested and working properly on HA 0.116.4.
> Xiaomi Mi Scale V2 BLE (XMTZC05HM) configuration

- main/ZgatewayBT.ino
Before the fix:
{"id":"58:2D:34:50:A0:D0","name":"Qingping Alarm Clock","rssi":-82,"distance":11.4949,"servicedata":"080cd0a050342d580104c0007c02"}
The servicedata string does not match any pattern so is not parsed
After the fix:
{"id":"58:2D:34:50:A0:D0","name":"Qingping Alarm Clock","rssi":-83,"distance":12.61001,"model":"CGD1","tem":19.2,"tempc":19.2,"tempf":66.56,"hum":63.5}
The parser is invoked and the data is output as expected.
There are probably too many brackets (I'm not a C dev) and I can't test on whatever version of CGD1 broadcasts 080caf or 080c09 servicedata strings. First tested on 0.9.4 with ESP32 (ran for months without issue). Now updating all my gateways to 0.9.5 and remembered to create the pull request.
> Fix/update to Qingping Cleargrass CGD1 detection

- .gitignore
- docs/use/rf.md
- main/ZgatewayPilight.ino
- main/config_RF.h
Enables usage of the new raw repeats parsing in ESPiLight 0.17.0. Now users can specify the `r:` parameter in their raw string to specify how many times their raw message should be repeated (previously, the default was 10, and is still 10 if the user does not specify it).
Also: removes the unused `PilightRAW` macro and adds macOS's `.DS_Store` files to the ignore list.
> Add ability to specify repeats for raw Pilight strings

- main/User_config.h
Allow time_avoid_duplicate to be configured by build_flags.
> ifndef condition for time_avoid_duplicate

- main/ZmqttDiscovery.ino
Enable HASS to retrieve data of remote sensors from multiple gateways by using wildcards for the location (instead of default:home) and the gateway name (instead of default:OpenMQTTGateway)
> Implement multi gateways discovery

- main/ZmqttDiscovery.ino
- main/main.ino
Parameters like battery/Vin voltage, the current will now be autodiscovered on M5Stick C, C plus.
M5Stack advertise Battery level, full and if charging.
Note that these parameters can be useful to detect a power outage.
[BREAKING] the key of the parameters are changed, the previous ones containing "-" were not autodiscovered
> {Breaking] Add M5 SYS parameters to auto discovery

- main/ZgatewayBT.ino
- main/ZgatewayRF.ino
- main/ZgatewayRF2.ino
- main/ZmqttDiscovery.ino
- main/ZsensorDS1820.ino
- main/config_mqttDiscovery.h
As discuted here: https://github.com/1technophile/OpenMQTTGateway/issues/821
Note that I'm not so good with C++, so I guess the code it's no so clean ...
> HASS Discovery - Create BLE devices automatically to gather entities

- platformio.ini
Adds environment directive to platform.io for Sonoff RF Bridge modified with "direct hack" allowing bypass of efm8bb1 microcontroller.  ( https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack ).
> sonoff rfbridge direct hack - first commit

- main/ZgatewayIR.ino
When building v0.9.5 on Arduino IDE 1.8.13, in either macOS 10.15.17 (Catalina) or 11.1 (Big Sur), I got this error:
```c
ZgatewayIR:258:90: error: 'sendIdentifiedProtocol' was not declared in this scope
signalSent = sendIdentifiedProtocol(protocol_name, data, hex, valueBITS, valueRPT);
^
```
This fix declares the `sendIdentifiedPRotocol` function, so the `MQTTtoIR` one compiles it.
I could also just swap the order, or try to simplify the declaration (if possible; wasn't sure about style/side effects), just let me know!
Thanks again for maintaining this amazing application.
<details>
<summary>Full error log</summary>
```
Arduino: 1.8.13 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB …
```
> Declare sendIdentifiedPRotocol so MQTTtoIR finds it

- main/config_RF.h
Received signals are published to the subjectRF2toMQTT topic (/RF2toMQTT). However, echos of mqtt messages are published to the topic subjectGTWRF2toMQTT (/433toMQTT).
That seems quite inconsistent and breaks functionality in Home Assistant that expects confirming messages, like this echo, on the same topic as receive messages.
This PR fixes this.
**Breaking change**
This PR changes the topic of echo messages. Configurations expecting the previous topic `433toMQTT`, will break.
Alternatively it might be an option to publish echos to both topics or make the topic configurable. Please let me know if such changes are preferred.
> [Breaking] Publish state to same channel as received signals

- docs/integrate/home_assistant.md
Found how to set this up in the issues, so I figured I'd add it to the docs because it works great for me
> added room presence yaml to docs

- main/ZgatewayBT.ino
- main/config_BT.h
- main/main.ino
Lockless queue for ESP32 BT as discussed.
Note, in theory the dumpDevices also could crash at MQTTtoBT, didn't touched that (yet).
> BT lockless queue

- docs/use/ble.md
- main/ZgatewayBT.ino
- main/ZgatewayWeatherStation.ino
- main/ZsensorDHT.ino
- main/ZsensorDS1820.ino
- main/ZsensorSHTC3.ino
- main/config_DS1820.h
- main/config_mqttDiscovery.h
we rely now on `tempc `and `tempf `only
> [BREAKING] remove tem key

- docs/use/gateway.md
- docs/use/rf.md
- main/User_config.h
- main/ZgatewayRTL_433.ino
- main/config_RF.h
- main/main.ino
- platformio.ini
This is my pull request with initial support for using the rtf_433 device decoders on a ESP32 board with a CC1101 Transceiver attached.  Please note that this initial port of the rtf_433 device decoders were brute forced over, to determine the usability of the decoders on in this form factor.
Due to memory and other resource constraints of the rtf_433 device decoders I did not include this in esp32dev-all-test environment, but created a new environment esp32dev-rtl_433.
PS I added a new cmd to the base set to trigger a status message from openMQTTGateway
PSS and fixed a defect when mqttdiscovery is not enabled
> Initial pull request for rtl_433 support

- main/User_config.h
- main/main.ino
#575
so as to see if in conjunction with the platforms update we get a better stability of wifi.
We are using this function since v0.9.3 but in my point of view, it should be handled at a lower level. 
I'm afraid that keeping it at the application level is creating more instability than stability. So let's remove it and test this branch and maybe the v0.9.6beta like that.
We will see if we keep it removed for the v0.9.6
> Remove wifi protocol auto change

- main/main.ino
Deep sleep should be activated only when failing connect on low power mode.
Correct reconnection on esp8266. Unfortunately WiFi.reconnect(); prevent the esp8266 from reconnecting, so we reduce its scope to ESP32
> Wifi reconnection improvements

- docs/use/ble.md
- main/ZgatewayBT.ino
- main/ZmqttDiscovery.ino
- main/config_BT.h
Useful if you want to scan continuously for BLE devices, in this case, you should deactivate the BLE connect to avoid concurrency between scan and connect callback
> Enable deactivation of BLE connect

- main/ZgatewayBT.ino
- main/config_BT.h
- platformio.ini
-low power mode settings example
-take into account parameters following #891
-add esp32dev-ble-cont for door/window sensor listening
> BLE low power mode and settings optimization
